In [6]:
import torch
import numpy as np

In [11]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [12]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [13]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [14]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.2806, -1.1222,  0.0901],
        [-0.4176, -0.7354, -0.7890]], requires_grad=True)
tensor([-0.5290, -0.1779], requires_grad=True)


In [15]:
def model(x):
    return x @ w.t() + b

In [16]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -51.3618, -113.8661],
        [ -67.9866, -153.3966],
        [-121.2726, -180.8214],
        [ -16.8306, -103.5934],
        [ -82.5976, -154.8259]], grad_fn=<AddBackward0>)


In [17]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [23]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(41916.4141, grad_fn=<DivBackward0>)


In [27]:
# Compute gradients
loss.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [26]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.2806, -1.1222,  0.0901],
        [-0.4176, -0.7354, -0.7890]], requires_grad=True)
tensor([[-11813.1738, -14397.5371,  -8503.2158],
        [-19421.8594, -21818.1602, -13351.8066]])
