In [1]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [7]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126



[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import torch
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name()}")
else:
    print("GPU is not available")

GPU is not available


In [5]:
#scalar
x = torch.tensor(3.14)
x

tensor(3.1400)

In [11]:
a = torch.empty(2, 4)
a

tensor([[2.9559e-11, 7.5670e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [12]:
torch.rand(3, 5, 2)

tensor([[[0.7580, 0.9509],
         [0.2480, 0.9781],
         [0.9431, 0.4382],
         [0.6702, 0.9006],
         [0.0545, 0.5914]],

        [[0.5808, 0.4984],
         [0.6691, 0.0314],
         [0.6303, 0.9788],
         [0.8203, 0.9491],
         [0.7869, 0.8714]],

        [[0.7152, 0.6575],
         [0.3585, 0.8939],
         [0.3590, 0.5435],
         [0.5624, 0.3551],
         [0.8717, 0.2430]]])

In [13]:
f = torch.arange(1, 10, 2)
f.shape

torch.Size([5])

In [14]:
a = torch.tensor([1, 4, 5])
b = torch.tensor([2, 3, 4])

c = torch.matmul(a, b)
c

tensor(34)

In [15]:
i = torch.ceil(torch.tensor([1.2, 2.5, 3.7]))
i


tensor([2., 3., 4.])

In [16]:
sum = torch.sum(torch.tensor([1, 2, 3, 4]))
sum

tensor(10)

In [17]:
e = torch.randint(size=(2, 3), low=0, high=int(1e5), dtype=torch.float32)
torch.rand(2, 3, 5)

tensor([[[0.1825, 0.6319, 0.7149, 0.4351, 0.3979],
         [0.5676, 0.7407, 0.5088, 0.6372, 0.6132],
         [0.3076, 0.9797, 0.3097, 0.9126, 0.0928]],

        [[0.2358, 0.8279, 0.2122, 0.3896, 0.5053],
         [0.9924, 0.0726, 0.7606, 0.5847, 0.3135],
         [0.1290, 0.7810, 0.4060, 0.8025, 0.6374]]])

In [18]:
torch.mean(e)
torch.std(e)

tensor(33899.4766)

In [19]:
x = torch.rand(size=(2, 3), dtype=torch.float32)
print(x.dtype)

y = x.type(torch.int32)
print(y.dtype)

torch.float32
torch.int32


In [20]:
a = torch.rand(size=(5, 2), dtype=torch.float32)
b = torch.rand(size=(2, 3), dtype=torch.float32)
print(a)
print(b)

c = torch.matmul(a, b)
print(c)

tensor([[0.7362, 0.7984],
        [0.3102, 0.2372],
        [0.6010, 0.0888],
        [0.9182, 0.3174],
        [0.2492, 0.2290]])
tensor([[0.9645, 0.0020, 0.7989],
        [0.7683, 0.3118, 0.9671]])
tensor([[1.3235, 0.2504, 1.3603],
        [0.4814, 0.0746, 0.4772],
        [0.6479, 0.0289, 0.5660],
        [1.1294, 0.1008, 1.0405],
        [0.4163, 0.0719, 0.4206]])


In [25]:
a_new = a.reshape(1, 10)
a_new

tensor([[0.7362, 0.7984, 0.3102, 0.2372, 0.6010, 0.0888, 0.9182, 0.3174, 0.2492,
         0.2290]])

In [6]:
r = torch.tensor([[2, 4, 5],[3, 5, 6]])
r.shape
print(r)
print(r.squeeze())

tensor([[2, 4, 5],
        [3, 5, 6]])
tensor([[2, 4, 5],
        [3, 5, 6]])
